services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mongo
    networks:
      - app-network
  search:
    build: ./simple_search
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    networks:
      - app-network
  mongo:
    image: "mongo:latest"
    restart: always
    networks:
      - app-network
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: campusclaim
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - .data:/var/lib/postgresql/data
    networks:
      - app-network
  nginx:
    image: staticfloat/nginx-certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d:ro
    environment:
      CERTBOT_EMAIL: desmondopokumends2004@gmail.com
      CERTBOT_DOMAIN: api.campusclaim.tech
    networks:
      - app-network
