services:
  backend:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mongo
  search:
    build: ./simple_search
    ports:
      - "8000:8000"
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
    restart: always
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: campusclaim
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - .data:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email desmondopokumends2004@gmail.com -d api.campusclaim.tech --agree-tos